image: ruby:2.1

before_script:
  - apt-get update && apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip -O /tmp/terraform.zip
  - mkdir -p /opt/terraform/bin
  - unzip -d /opt/terraform/bin /tmp/terraform.zip
  - ln -s /opt/terraform/bin/terraform /usr/bin/terraform
  - rm /tmp/terraform.zip
  - mkdir /root/.ssh && chmod 0600 /root/.ssh
  - echo ${PROVISIONER_KEY} >/root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa

test:
  variables:
    TF_VAR_region: "{ primary = "us-east-1", secondary = "us-west-2" }"
  script:
  - eval $(ssh-agent)
  - pwd
  - terraform plan
  only:
  - master
