image: ruby:2.1

before_script:
  - apt-get update && apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip -O /tmp/terraform.zip
  - mkdir -p /opt/terraform/bin
  - unzip -d /opt/terraform/bin /tmp/terraform.zip
  - ln -s /opt/terraform/bin/terraform /usr/bin/terraform
  - rm /tmp/terraform.zip
  - mkdir /root/.aws
  - echo "[default]" >/root/.aws/credentials && chmod 0600 /root/.aws/credentials
  - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >>/root/.aws/credentials
  - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >>/root/.aws/credentials

deploy_ci_env:
  script:
  - eval $(ssh-agent -s)
  - echo "${PROVISIONER_KEY}" | ssh-add -
  - echo "terraform {" >remote_state.tf
  - echo "  backend \"s3\" {" >>remote_state.tf
  - echo "    bucket  = \"my-tf-state-files\"" >>remote_state.tf
  - echo "    key     = \"tf_gitlab_test/ci-state.tfstate\"" >>remote_state.tf
  - echo "    region  = \"us-west-2\"" >>remote_state.tf
  - echo "    profile = \"default\"" >>remote_state.tf
  - echo "  }" >>remote_state.tf
  - echo "}" >>remote_state.tf
  - cat remote_state.tf
  - terraform init
  - terraform plan
  only:
  - master
